apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
     app: app-deployment
     type: front-end
spec:
  template:
     metadata:
       name: app-deployment
       labels: 
         app: app-deployment
         type: front-end
     spec:
         containers:
           - name: app-deployment
             image: "rajeshshirke/img2:latest"
  replicas: 2
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-deployment
  type: NodePort  
  ports:
    - protocol: TCP
      targetPort: 30000
      port: 80
