apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-DevOps-Project-2
  labels:
     app: app-deployment
spec:
  template:
     metadata:
       labels: 
         app: app-deployment
     spec:
       containers:
       - name: app-deployment
         image: "rajeshshirke/img2:latest"
         ports:
         - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: app-deployment 

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-deployment
  type: LoadBalancer  
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 5000
    NodePort: 31110
