apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-DevOps-Project-2
  labels:
     app: app-deployment
spec:
  template:
     metadata:
       labels: 
         app: app-deployment
     spec:
       containers:
       - name: app-deployment
         image: "rajeshshirke/img2:latest"
         ports:
         - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: app-deployment
